apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nfd
  name: nfd-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfd-master
  template:
    metadata:
      labels:
        app: nfd-master
    spec:
      serviceAccount: nfd-master
      enableServiceLinks: false
      tolerations: []
      containers:
        - name: nfd-master
          image: registry.k8s.io/nfd/node-feature-discovery:v0.17.2
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 300m
              memory: 4Gi
            requests:
              cpu: 100m
              memory: 128Mi
          startupProbe:
            grpc:
              port: 8082
            failureThreshold: 30
          livenessProbe:
            grpc:
              port: 8082
          readinessProbe:
            grpc:
              port: 8082
            failureThreshold: 10
          command:
            - "nfd-master"
          ports:
            - name: metrics
              containerPort: 8081
