apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nfd
  name: nfd-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfd-master
  template:
    metadata:
      labels:
        app: nfd-master
    spec:
      serviceAccount: nfd-master
      tolerations: []
      containers:
        - name: nfd-master
          image: gcr.io/k8s-staging-nfd/node-feature-discovery:master
          imagePullPolicy: Always
          command:
            - "nfd-master"
          args: []
          volumeMounts: []
      volumes: []
