{{- if .Values.master.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "node-feature-discovery.fullname" . }}-master-network-policy
  namespace: {{ include "node-feature-discovery.namespace" . }}
  labels:
    {{- include "node-feature-discovery.labels" . | nindent 4 }}
    role: master
spec:
  egress:
    {{- with .Values.master.networkPolicy.egress }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  ingress:
    {{- with .Values.master.networkPolicy.ingress }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  podSelector:
    matchLabels:
      {{- include "node-feature-discovery.selectorLabels" . | nindent 6 }}
      role: master
  policyTypes:
  - Egress
  - Ingress
{{- end }}
